name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install .
          pip install pycodestyle

      - name: PEP8
        run:
          pycodestyle --config=./setup.cfg .

      - name: Run tests
        run:
          python -m unittest discover -s ./tests -p '*tests.py'
